_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/rtdetr_r50vd.yml',
  '_base_/rtdetr_reader.yml',
]

weights: D:\py12\aim\PaddleDetection-develop\123\zuizhongmoxingquanzhong\best_model.pdparams
find_unused_parameters: True
log_iter: 200
