_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_500e.yml',
  '_base_/yolov8_cspdarknet.yml',
  '_base_/yolov8_reader.yml',
]
depth_mult: 0.33
width_mult: 0.25

log_iter: 50
snapshot_epoch: 10
weights: C:/Users/10614/Downloads/yolov8_n_500e_coco.pdparams


TrainReader:
  batch_size: 16 # default 8 gpus, total bs = 128
